# -*- coding: utf-8 -*-
"""Demand Forecasting for a Retail Store.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oqcCcVYoeKdLjzyjf5kJYHmZNe4qXk95
"""

# Import necessary libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import statsmodels.api as sm
from statsmodels.tsa.seasonal import seasonal_decompose
from statsmodels.tsa.statespace.sarimax import SARIMAX

# Load historical sales data (replace 'your_file.csv' with your actual data file)
data = pd.read_csv('scanner_data.csv')
sales = data['Sales']  # assuming 'sales' is the column with historical sales data

# Visualize the data
plt.figure(figsize=(12,5))
plt.plot(sales.index, sales.values, color='blue')
plt.title('Historical Sales Data')
plt.xlabel('Date')
plt.ylabel('Quanity')
plt.show()

# Decompose the time series to observe seasonality and trends
decomposition = seasonal_decompose(sales, model='multiplicative', period=12)  # assuming 12 months seasonality
decomposition.plot()
plt.show()

# Fit a SARIMA model
mod = SARIMAX(sales, order=(1,1,1), seasonal_order=(1,1,1,12))
results = mod.fit()

# Forecast future demand
forecast, stderr, conf_int = results.forecast(steps=12)  # assuming 12 months forecast

# Print the forecast
print("Forecast: ", forecast)

